# config.yaml
experiments:
  experiment:
    data_dir: "data/front"
    ext: "png"
    n: "24"
    sc: "body"
    c: "front"
    tp: "0.7"
    num_keypoints: "24"
    flip_fairs: "[[1,4],[2,3],[5,7],[6,8],[9,10],[11,12],[13,14],[15,16],[17,19],[18,19],[21,23],[22,24]]"
    data_format: "png"
    data_root: "data/front"
    begin_epoch: "50"
    end_epoch: "300"
    config_file: "experiments/Auto/hrnet/w48_384x288_adam_lr1e-3.yaml"
    output_file: "experiments/Auto/hrnet/w48_384x288_adam_lr1e-3_auto_kube.yaml"
    pretrained_model: "models/pose_hrnet-w48_384x288-deepfashion2_mAP_0.7017.pth"
    run_name: "NTO_test"
  # 필요에 따라 추가 실험 항목을 넣을 수 있음
